intake_task:
  description: >
    Analyze the following list of user tasks submitted in natural language:

    {user_tasks}

    Convert them into structured data entries. Each entry should include:
    - Title
    - Category (Work / Personal / Other)
    - Priority (High / Medium / Low)
    - Deadline (if present, otherwise leave blank).
  expected_output: >
    A markdown table with columns: Title, Category, Priority, Deadline.
  agent:
    task_intake_specialist

planning_task:
  description: >
    Given the structured table from the previous step, organize these tasks into a daily schedule for today.

    Divide the schedule into time blocks (Morning, Afternoon, Evening), and list the most urgent or high-priority tasks earlier.
  expected_output: >
    A markdown-formatted day schedule organized by time blocks, with tasks assigned to each.
  agent: task_planner